### PR TITLE
WebGLRenderer: Fix shadow map shader regression.

### LINKED ISSUE #25247: Shader compilation error with SpotLight and DirectionalLight/PointLight but no shadow map
### Description

Vertex shaders of materials using shadowmaps fail to compile if there is at least one SpotLight and one DirectionalLight or PointLight in the scene casting shadows, but the shadowmap is not enabled.

The critical part of the error message is `'directionalLightShadows' : undeclared identifier`.

This is probably due to the change introduced in https://github.com/mrdoob/three.js/pull/24564 , where the following condition:
 https://github.com/mrdoob/three.js/blob/f19f1406667bcdf41e09d8ccfc11ffc8af6d3f33/src/renderers/shaders/ShaderChunk/shadowmap_vertex.glsl.js#L2 
 
 ...included `|| ( NUM_SPOT_LIGHT_COORDS > 0 )`, while the definition:
 https://github.com/mrdoob/three.js/blob/f19f1406667bcdf41e09d8ccfc11ffc8af6d3f33/src/renderers/shaders/ShaderChunk/shadowmap_pars_vertex.glsl.js#L24
 
 ... is conditioned on `#ifdef USE_SHADOWMAP` and `#if NUM_DIR_LIGHT_SHADOWS > 0` only. That is, the identifier `directionalLightShadows` only gets defined when there is a shadow map and some directional lights. However, it gets used regardless of shadow map if there are any spot lights. The same holds for point lights.
 

### Reproduction steps

1. Add a SpotLight and a Directional/PointLight to a scene.
2. Make them both cast shadows.
3. Add an object with MeshStandardMaterial which receives shadows.
4. Make sure the shadowMap on the renderer is not enabled.
5. Render the scene and observe the compilation error.

### Code

```js
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera();

const renderer = new THREE.WebGLRenderer();
renderer.shadowMap.enabled = false; // this is the default

const geometry = new THREE.PlaneGeometry();
const material = new THREE.MeshStandardMaterial();
const plane = new THREE.Mesh( geometry, material );
plane.receiveShadow = true;
scene.add( plane );

const directionalLight = new THREE.DirectionalLight();
directionalLight.castShadow = true;
scene.add( directionalLight );

const spotLight = new THREE.SpotLight();
spotLight.castShadow = true;
scene.add( spotLight );

renderer.render( scene, camera ); // error

```

### Live example

[jsfiddle-latest-release](https://jsfiddle.net/sj6tqeb7/1/) (see the console output)

### Screenshots

_No response_

### Version

r148

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #25247.

**Description**

The if statements in `shadowmap_vertex` need a different organization to avoid the compilation error mentioned in #25247.

### CODE REVIEW

File: src/renderers/shaders/ShaderChunk/shadowmap_vertex.glsl.js [hunk 1]
```diff
@@ -60,4 +45,24 @@ export default /* glsl */`
 	*/
 
 #endif
+
+// spot lights can be evaluated without active shadow mapping (when SpotLight.map is used)
```
Comment (Mugen87) [inline src/renderers/shaders/ShaderChunk/shadowmap_vertex.glsl.js:49]: I hope this comment makes it clear why the below code is executed without a `USE_SHADOWMAP` definition.
