### ISSUE TITLE
Logarithmic Depth breaks MeshNormalMaterial

### ISSUE THREAD

**Issue by vanruesc** [mrdoob/three.js#17629]
#### Description of the problem

Enabling `logarithmicDepthBuffer` causes a shader compilation error in `MeshNormalMaterial`:

```sh
THREE.WebGLShader: gl.getShaderInfoLog() vertex
ERROR: 0:204: 'isPerspectiveMatrix' : no matching overloaded function found
1: precision highp float;
2: precision highp int;
3: #define HIGH_PRECISION
4: #define SHADER_NAME MeshNormalMaterial
```

The following example shows the problem (uncomment line 24):
https://jsfiddle.net/k0p8d4j7/

#### Full Error Log

[jsfiddle.net-1569930124580.log](https://github.com/mrdoob/three.js/files/3676002/jsfiddle.net-1569930124580.log)

#### Three.js version

- [x] Dev
- [x] r109
- [ ] r108

#### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

#### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Comment by gkjohnson** [comment]
It looks like this also broke with #17442.

It's breaking because the `isPerspectiveMatrix` function is defined in the `<common>` shader chunk but the normal material doesn't include `<common>`.

It can be fixed by adding that to the top of the normal material. I can make another PR later tonight.
