### ISSUE TITLE
Uncaught TypeError: font.generateShapes is not a function

### ISSUE THREAD

**Issue by genzzo** [mrdoob/three.js#23672]
```Uncaught TypeError: font.generateShapes is not a function``` when trying to create a text geometry 
Following the code leads to ```const shapes = font.generateShapes( text, parameters.size );```

This is my code:
```js
import { TextGeometry } from 'three/examples/jsm/geometries/TextGeometry'
import font from 'three/examples/fonts/helvetiker_regular.typeface.json'

const textGeometry = new TextGeometry('This is a 3d font', {
    font: font,
})
```
Notes:
- The initial code included all other parameters but I removed them to limit the error
- I am using parcel as my development server
- I have also used font loader and a different issue popped up saying ```Uncaught (in promise) SyntaxError: Unexpected token e in JSON at position 0```, I commented the origin of the error only to bounce back to this one

**Comment by Mugen87** [comment]
Please use the [forum](https://discourse.threejs.org/) for help requests.

> Uncaught (in promise) SyntaxError: Unexpected token e in JSON at position 0

It seems your font is not properly loaded which could lead to the above error. Please clarify this in the forum and also share _a live example that demonstrates the runtime error._

**Comment by genzzo** [comment]
Will do.

But this font is the one in the three.js examples file, and it gave the same result as any external font and any other three.js font I've tried.

And that doesn't really hit the spot for me because as I've mentioned I've maneuvered around the error but got stuck with the textGeometry.

**Comment by Mugen87** [comment]
Other users had the same issue in the past and the reason for `Uncaught TypeError: font.generateShapes is not a function` is that the passed in font is not of type `THREE.Font`. Usually something goes wrong with the loading process.

**Comment by genzzo** [comment]
Kinda weird considering I am using the provided three.js font, and that I used the provided tool on the website for creating JSON fonts. But I guess that makes sense as it didn't contain the attributes for generating shapes when I logged it in the console.

Thank you either way, I'll see what I can do about it.

**Comment by jjwall** [comment]
Getting this same error after updating from 0.137.0 to 0.146.0. Is it possible there was an API refactor removing the Font module altogether?
