### ISSUE TITLE
Creating a mesh from Vertices

### ISSUE THREAD

**Issue by unreturnable** [mrdoob/three.js#6773]
I'm trying to create a Mesh from vertices using this code:

``` javascript
getMeshFromVertices = function(vertices, holes) {
        var triangles, mesh;
        var geometry = new THREE.Geometry();
        var material = new THREE.MeshBasicMaterial();

        geometry.vertices = vertices;
        triangles = THREE.Shape.Utils.triangulateShape(vertices, holes);

        for( var i = 0; i < triangles.length; i++ ){
            geometry.faces.push(new THREE.Face3(triangles[i][0], triangles[i][1], triangles[i][2]));
        }

        return new THREE.Mesh(geometry, material);
    }
```

But when I do this I get this error:

```
Uncaught TypeError: contour.concat is not a function
THREE.Shape.Utils.triangulateShape @ three.js:29200
```

When I go to that line in the Three.js source I discover this is what its trying to do:

``` javascript
var allpoints = contour.concat();
```

Which isn't ever going to work. There is a similar problem on line 29254.

``` javascript
return triangles.concat();
```

All of this is taken from revision 71.

**Comment by WestLangley** [comment]
As stated in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md), help requests should be directed to [stackoverflow](http://stackoverflow.com/questions/tagged/three.js). This board is for bugs and feature requests.

If you are not sure if it is a three.js bug, we prefer you first seek help on stackoverflow.

If you can demonstrate a three.js bug, please provide a test case so we can reproduce your results. Please see "How to report a bug" in the [guidelines](https://github.com/mrdoob/three.js/blob/master/CONTRIBUTING.md).

**Comment by unreturnable** [comment]
As far as I'm aware the code I'm using to create the mesh has worked in previous versions of Three.js. Don't know which versions though and haven't had a chance to test this yet. There is no way it can work in the current version though due to those .concat's

**Comment by unreturnable** [comment]
WestLangley, There is no way this code can ever run. Concat requires 1 argument which the Three.js source shown doesn't provide. Therefore this is a bug with Three.js and not a tutorial point.

**Comment by WestLangley** [comment]
Hmmm. The call to `concat()` without args was added to `Shape.js` in r.66...

**Comment by unreturnable** [comment]
I think I might have found the source of the issue, my data I'm feeding into that method changes and is some times formatted oddly. Sorry for being over eager to report and issue, although I'm still confused as to what the purpose of those lines of code is.

**Comment by WestLangley** [comment]
> I'm still confused as to what the purpose of those lines of code is.

Me too.

/ping @zz85

**Comment by makc** [comment]
concat without arguments = shallow clone of array. but this:
```
		var allpoints = contour.concat();

		for ( var h = 0, hl = holes.length; h < hl; h ++ ) {

			Array.prototype.push.apply( allpoints, holes[h] );

		}
```
suggests that contour is not expected to have push method, how can it have concat then? which is exactly what error message says
> contour.concat is not a function

but Array.prototype.concat.apply would not work (in firefox at least), you need Array.prototype.slice.apply

**Comment by zz85** [comment]
yes `bla.concat()` returns a copy of the array. `Array.prototype.push` seems to be introduced in commit 4b144ff31bfa814f264ec35e55de0d98051f2ac1. I don't remember why it is used. Maybe we can reopen this issue.

**Comment by WestLangley** [comment]
@zz85 Reopened, as requested. Do you mind having a further look?

**Comment by zz85** [comment]
sorry it took awhile, but it looks like the functionality in the code is correct. holes is a nested array of vector like `[ [ v1, v2... ] ]`.

```
for ( var h = 0, hl = holes.length; h < hl; h ++ ) {

            Array.prototype.push.apply( allpoints, holes[h] );

        }
```
is a shortcut for

```
for ( var h = 0, hl = holes.length; h < hl; h ++ ) {
   var list = holes[h];
    for ( var i = 0; i < list; i++ ) {
       allpoints.push( list[ i ] )
    }
}
```

anyways it also can be written as `allpoints.push.apply( allpoints, holes[h] );`

**Comment by bag-man** [comment]
@unreturnable  Hi, I came across this code looking for something else, would you know if THREE.Shape.Utils is still available in r82?

As I don't seem to have access to it, with just three.js, do I need to include another lib?

**Comment by mrdoob** [comment]
It is now `THREE.ShapeUtils`.

**Comment by bag-man** [comment]
Nice one thanks, can't find it in the docs anywhere though!

**Comment by Mugen87** [comment]
@bag-man Docs were added by @looeee with #10042
